services:
  postgres_auth:
    image: postgres:16
    container_name: auth-postgres
    restart: unless-stopped
    networks:
      - internal_net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_HASH: ${ADMIN_HASH}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./db/02-init-admin.sh:/docker-entrypoint-initdb.d/02-init-admin.sh
    ports:
      - "5432:5432"

  auth-service:
    build: .
    container_name: auth-service
    restart: unless-stopped
    networks:
      - shared_network
      - internal_net
    depends_on:
      - postgres_auth
    environment:
      DB_HOST: postgres_auth
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_SSLMODE: disable
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
    volumes:
      - ./keys/private.pem:/app/keys/private.pem:ro
      - ./keys/public.pem:/app/keys/public.pem:ro
    ports:
      - "8080:8080"


volumes:
  pgdata:

networks:
  internal_net:
  shared_network:
    external: true